title: Hope Community Church
author: hope-community
email: hopechurchnorman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website for Hope Community Church in Norman, OK
github_username:  hopechurchnorman
plugins:
  - jekyll-seo-tag
